// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALUS7E5fYJDI0mrcXWdahQ0d6TUKXs7fA',
    appId: '1:286072090024:web:d8c08532f528745261419d',
    messagingSenderId: '286072090024',
    projectId: 'bloom-da824',
    authDomain: 'bloom-da824.firebaseapp.com',
    storageBucket: 'bloom-da824.appspot.com',
    measurementId: 'G-ZTL6S21MJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn30wcImgifv2KeWyaKJhhsz_HJ2EDDIs',
    appId: '1:286072090024:android:467e47f76663bf1161419d',
    messagingSenderId: '286072090024',
    projectId: 'bloom-da824',
    storageBucket: 'bloom-da824.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVn8PRRNHbwi8iu1OYfO90HS6-uHEtq9Q',
    appId: '1:286072090024:ios:1cf7c9eb6111343661419d',
    messagingSenderId: '286072090024',
    projectId: 'bloom-da824',
    storageBucket: 'bloom-da824.appspot.com',
    iosBundleId: 'com.bloomproductive.bloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVn8PRRNHbwi8iu1OYfO90HS6-uHEtq9Q',
    appId: '1:286072090024:ios:1cf7c9eb6111343661419d',
    messagingSenderId: '286072090024',
    projectId: 'bloom-da824',
    storageBucket: 'bloom-da824.appspot.com',
    iosBundleId: 'com.bloomproductive.bloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALUS7E5fYJDI0mrcXWdahQ0d6TUKXs7fA',
    appId: '1:286072090024:web:2bc96a01da99519761419d',
    messagingSenderId: '286072090024',
    projectId: 'bloom-da824',
    authDomain: 'bloom-da824.firebaseapp.com',
    storageBucket: 'bloom-da824.appspot.com',
    measurementId: 'G-4LG5QCBV4X',
  );
}
